### PR TITLE
node: mempool - reject moonlight txs with non consecutive nonce

### LINKED ISSUE #2605: testnet: moonlight-stake transaction stuck in the mempool
**Describe the bug**
Moonlight stake transaction stuck in the mempool and not included in the block.

**To Reproduce**
```
rusk-wallet --log-level trace moonlight-stake --amt 1000
```

**Logs/Screenshot**

```
2024-10-06T00:29:53.015925Z TRACE hyper_util::client::legacy::pool: checkout waiting for idle connection: ("https", nodes.dusk.network)
2024-10-06T00:29:53.020586Z TRACE hyper_util::client::legacy::connect::http: Http::connect; scheme=Some("https"), host=Some("nodes.dusk.network"), port=None
2024-10-06T00:29:53.021377Z DEBUG resolve{host=nodes.dusk.network}: hyper_util::client::legacy::connect::dns: resolving host="nodes.dusk.network"
2024-10-06T00:29:53.022433Z DEBUG hyper_util::client::legacy::connect::http: connecting to 188.72.231.50:443
2024-10-06T00:29:53.057828Z DEBUG hyper_util::client::legacy::connect::http: connected to 188.72.231.50:443
2024-10-06T00:29:53.469772Z TRACE hyper_util::client::legacy::client: http1 handshake complete, spawning background dispatcher task
2024-10-06T00:29:53.469826Z TRACE hyper_util::client::legacy::pool: checkout dropped for ("https", nodes.dusk.network)
2024-10-06T00:29:54.010180Z TRACE hyper_util::client::legacy::pool: pool dropped, dropping pooled (("https", nodes.dusk.network))
2024-10-06T00:29:54.022817Z TRACE hyper_util::client::legacy::pool: checkout waiting for idle connection: ("https", provers.dusk.network)
2024-10-06T00:29:54.022840Z TRACE hyper_util::client::legacy::connect::http: Http::connect; scheme=Some("https"), host=Some("provers.dusk.network"), port=None
2024-10-06T00:29:54.022871Z DEBUG resolve{host=provers.dusk.network}: hyper_util::client::legacy::connect::dns: resolving host="provers.dusk.network"
2024-10-06T00:29:54.023408Z DEBUG hyper_util::client::legacy::connect::http: connecting to 188.72.231.50:443
2024-10-06T00:29:54.061388Z DEBUG hyper_util::client::legacy::connect::http: connected to 188.72.231.50:443
2024-10-06T00:29:54.486171Z TRACE hyper_util::client::legacy::client: http1 handshake complete, spawning background dispatcher task
2024-10-06T00:29:54.486221Z TRACE hyper_util::client::legacy::pool: checkout dropped for ("https", provers.dusk.network)
2024-10-06T00:29:54.893112Z TRACE hyper_util::client::legacy::pool: put; add idle connection for ("https", provers.dusk.network)
2024-10-06T00:29:54.893142Z DEBUG hyper_util::client::legacy::pool: pooling idle connection for ("https", provers.dusk.network)
2024-10-06T00:29:54.893468Z  INFO rusk_wallet::io::status: status="Opening notes database"
2024-10-06T00:29:54.900819Z  INFO rusk_wallet::io::status: status="Fetching chain_id..."
2024-10-06T00:29:54.912950Z TRACE hyper_util::client::legacy::pool: checkout waiting for idle connection: ("https", nodes.dusk.network)
2024-10-06T00:29:54.912972Z TRACE hyper_util::client::legacy::connect::http: Http::connect; scheme=Some("https"), host=Some("nodes.dusk.network"), port=None
2024-10-06T00:29:54.913001Z DEBUG resolve{host=nodes.dusk.network}: hyper_util::client::legacy::connect::dns: resolving host="nodes.dusk.network"
2024-10-06T00:29:54.913648Z DEBUG hyper_util::client::legacy::connect::http: connecting to 188.72.231.50:443
2024-10-06T00:29:54.949436Z DEBUG hyper_util::client::legacy::connect::http: connected to 188.72.231.50:443
2024-10-06T00:29:55.354100Z TRACE hyper_util::client::legacy::client: http1 handshake complete, spawning background dispatcher task
2024-10-06T00:29:55.354194Z TRACE hyper_util::client::legacy::pool: checkout dropped for ("https", nodes.dusk.network)
2024-10-06T00:29:55.893352Z  INFO rusk_wallet::io::status: status="Chain id received!"
2024-10-06T00:29:55.893383Z  INFO rusk_wallet::io::status: status="Fetching account-data..."
2024-10-06T00:29:55.893352Z TRACE hyper_util::client::legacy::pool: pool dropped, dropping pooled (("https", nodes.dusk.network))
2024-10-06T00:29:55.908018Z TRACE hyper_util::client::legacy::pool: checkout waiting for idle connection: ("https", nodes.dusk.network)
2024-10-06T00:29:55.908041Z TRACE hyper_util::client::legacy::connect::http: Http::connect; scheme=Some("https"), host=Some("nodes.dusk.network"), port=None
2024-10-06T00:29:55.908067Z DEBUG resolve{host=nodes.dusk.network}: hyper_util::client::legacy::connect::dns: resolving host="nodes.dusk.network"
2024-10-06T00:29:55.908505Z DEBUG hyper_util::client::legacy::connect::http: connecting to 188.72.231.50:443
2024-10-06T00:29:55.941274Z DEBUG hyper_util::client::legacy::connect::http: connected to 188.72.231.50:443
2024-10-06T00:29:56.386535Z TRACE hyper_util::client::legacy::client: http1 handshake complete, spawning background dispatcher task
2024-10-06T00:29:56.386614Z TRACE hyper_util::client::legacy::pool: checkout dropped for ("https", nodes.dusk.network)
2024-10-06T00:29:56.929451Z  INFO rusk_wallet::io::status: status="account-data received!"
2024-10-06T00:29:56.929474Z  INFO rusk_wallet::io::status: status="Fetching stake..."
2024-10-06T00:29:56.929446Z TRACE hyper_util::client::legacy::pool: pool dropped, dropping pooled (("https", nodes.dusk.network))
2024-10-06T00:29:56.945849Z TRACE hyper_util::client::legacy::pool: checkout waiting for idle connection: ("https", nodes.dusk.network)
2024-10-06T00:29:56.945871Z TRACE hyper_util::client::legacy::connect::http: Http::connect; scheme=Some("https"), host=Some("nodes.dusk.network"), port=None
2024-10-06T00:29:56.945905Z DEBUG resolve{host=nodes.dusk.network}: hyper_util::client::legacy::connect::dns: resolving host="nodes.dusk.network"
2024-10-06T00:29:56.946423Z DEBUG hyper_util::client::legacy::connect::http: connecting to 188.72.231.50:443
2024-10-06T00:29:56.980806Z DEBUG hyper_util::client::legacy::connect::http: connected to 188.72.231.50:443
2024-10-06T00:29:57.433795Z TRACE hyper_util::client::legacy::client: http1 handshake complete, spawning background dispatcher task
2024-10-06T00:29:57.433863Z TRACE hyper_util::client::legacy::pool: checkout dropped for ("https", nodes.dusk.network)
2024-10-06T00:29:58.108576Z  INFO rusk_wallet::io::status: status="Stake received!"
Staking address: yLWh6C8gGG3PhkzMTz7WUTyXQLudWLN7EXu5PZaEaKJT3aQa2Sf9kodH4HF3WQK3mUfh5edqsGEBjW9pq6JHLigezJPZyYnUAnjMRuKFstBktwf5rSw1TgD8Dwz1SmNi6nV
2024-10-06T00:29:58.108576Z TRACE hyper_util::client::legacy::pool: pool dropped, dropping pooled (("https", nodes.dusk.network))
2024-10-06T00:29:58.111370Z  INFO rusk_wallet::io::status: status="Attempt to preverify tx..."
2024-10-06T00:29:58.124153Z TRACE hyper_util::client::legacy::pool: checkout waiting for idle connection: ("https", nodes.dusk.network)
2024-10-06T00:29:58.124202Z TRACE hyper_util::client::legacy::connect::http: Http::connect; scheme=Some("https"), host=Some("nodes.dusk.network"), port=None
2024-10-06T00:29:58.124245Z DEBUG resolve{host=nodes.dusk.network}: hyper_util::client::legacy::connect::dns: resolving host="nodes.dusk.network"
2024-10-06T00:29:58.124814Z DEBUG hyper_util::client::legacy::connect::http: connecting to 188.72.231.50:443
2024-10-06T00:29:58.174611Z DEBUG hyper_util::client::legacy::connect::http: connected to 188.72.231.50:443
2024-10-06T00:29:58.600503Z TRACE hyper_util::client::legacy::client: http1 handshake complete, spawning background dispatcher task
2024-10-06T00:29:58.600553Z TRACE hyper_util::client::legacy::pool: checkout dropped for ("https", nodes.dusk.network)
2024-10-06T00:29:59.152053Z TRACE hyper_util::client::legacy::pool: put; add idle connection for ("https", nodes.dusk.network)
2024-10-06T00:29:59.152069Z DEBUG hyper_util::client::legacy::pool: pooling idle connection for ("https", nodes.dusk.network)
Rusk error occurred: 500 Internal Server Error: this transaction exists in the mempool
```

### PR DESCRIPTION
**Pull request by herr-seppia**
Mempool allows moonlight txs if they satisfy one of the following:
- tx.nonce() is equal to state.account.nonce()+1
- tx.nonce() is greater of state.account.nonce()+1 and all the intermediate nonces are in the mempool

Additionally:
- Fixed a bug that was preventing mempool secondary index to be populated with moonlight txs
- Improve mempool pruning to remove dependant transactions for expired or discarded txs

Resolves #2605

### CODE REVIEW

**Comment by AstronautDoggo** [comment]
LGTM

**Review by HDauven — APPROVED** [review]
LGTM

**Comment by herr-seppia** [comment]
@HDauven Need to refine a bit to avoid people start to attack the mempool in another way

give me 10min

File: node/src/mempool.rs [hunk 1]
```diff
@@ -242,8 +243,28 @@ impl MempoolSrv {
...
+        if let PreverificationResult::FutureNonce {
+            account,
+            state,
+            nonce_used,
+        } = preverification_data
+        {
+            db.read().await.view(|db| {
+                for nonce in state.nonce + 1..nonce_used {
+                    let spending_id = SpendingId::AccountNonce(account, nonce);
+                    if db.get_txs_by_spendable_ids(&[spending_id]).is_empty() {
```
Comment (HDauven) [inline node/src/mempool.rs:260]: Not needed for now, but in the future it would be interesting to see what an "inverse" implementation would do, where we pre-compute the AccountNonce. This should be limited to a maximum range to prevent spam attacks.

Since we limit the mempool to 10k transactions, we can already set that as a natural limit per account, but logically it would be a lower number.

If the current implementation is performant enough, I would discard this comment completely.

Comment (herr-seppia) [reply node/src/mempool.rs:260]: As you said, let's bench it

**Review by HDauven — DISMISSED** [review]
