### PR TITLE
Use `DeriveKey` in WFO/STCO messages

### LINKED ISSUE #407: Avoid using long list of anonymous parameters in methods
**Describe what you want implemented**
Rather accepting a long list (>3) of parameters it is preferable for methods and functions to accept a struct. Moreover, rather than creating the struct with a `new` function (i.e. re-anonymizing the parameters), the struct should be instantiated with named parameters

**Describe "Why" this is needed**
It dramatically increases the readability of the code and minimizes the chance for confusion

**Additional Context**
In the #400, it was decided to postpone the efforts to tackle tech debt to specific issues

_This is a regression, we should go back to avoiding prefixes (such as `input_`, `change_` and `output_`) and having types instead. It was already pointed out in a previous PR and that's why we changed in that way._

_Originally posted by @ZER0 in https://github.com/dusk-network/rusk/pull/400#discussion_r780271048_

### PR DESCRIPTION
**Pull request by herr-seppia**
- Avoid using a long list of anonymous parameters in methods.
- Remove anonymous `new` constructors in favour of explicit named parameters
- Regenerate rusk keys

Resolves #407

### CODE REVIEW

**Review by autholykos — APPROVED** [review]
LGTM. A good refactor for readability

File: circuits/transfer/tests/send_to_contract_obfuscated.rs [hunk 1]
```diff
@@ -55,8 +55,13 @@ fn create_random_circuit<R: RngCore + CryptoRng>(
...
 
-    let message =
-        StcoMessage::new(message, m_r, m_derive_key, m_pk_r, m_blinder);
+    let message = StcoMessage {
+        blinder: m_blinder,
+        derive_key: m_derive_key,
+        message,
+        pk_r: m_pk_r,
+        r: m_r,
+    };
```
Comment (ZER0) [inline circuits/transfer/tests/send_to_contract_obfuscated.rs:64]: couldn't use / reuse `blinder` instead of `m_blinder` (and the same for all the `m_` prefixed ones)…?

File: contracts/transfer/tests/transfer.rs [hunk 2]
```diff
@@ -383,29 +383,32 @@ fn withdraw_from_obfuscated() {
...
-
-    let wfo_output = WfoCommitment::new(
-        withdraw_value,
-        withdraw_blinder,
-        *withdraw.value_commitment(),
-    );
-
-    let wfo_circuit =
-        WithdrawFromObfuscatedCircuit::new(wfo_input, wfo_change, wfo_output);
+    let wfo_input = WfoCommitment {
```
Comment (ZER0) [inline contracts/transfer/tests/transfer.rs:386]: Why you didn't use a similar approach that you used for the obfuscated? Try to be consistent.

File: contracts/transfer/tests/wrapper/mod.rs [hunk 3]
```diff
@@ -614,13 +614,13 @@ impl TransferWrapper {
...
+            derive_key: message_derive_key,
             message,
-            message_r,
-            message_derive_key,
-            message_pk_r,
-            message_blinder,
-        );
+            pk_r: message_pk_r,
+            r: message_r,
+        };
```
Comment (ZER0) [inline contracts/transfer/tests/wrapper/mod.rs:623]: Same here.

File: rusk/build.rs [hunk 4]
```diff
@@ -215,8 +215,14 @@ mod transfer {
...
-            let message =
-                StcoMessage::new(message, m_r, m_derive_key, m_pk_r, m_blinder);
+            let message = StcoMessage {
+                blinder: m_blinder,
+                derive_key: m_derive_key,
+                message,
+                pk_r: m_pk_r,
+                r: m_r,
+            };
+
```
Comment (ZER0) [inline rusk/build.rs:225]: And here.

**Review by ZER0 — CHANGES_REQUESTED** [review]
A couple of questions and something that looks like a small inconsistency.
