### PR TITLE
web-wallet: Add message for no contracts enabled

### LINKED ISSUE #1317: Exception handling for disabled contracts
Currently, it's possible that a user will end up with no contracts enabled (if they're all disabled in the `env`).

I think it's good to introduce some error page / empty state for when no contracts have been enabled, giving some useful information to the user (I guess it would be mostly the developer in this case).

Generally, it feels like it will be more of a developer's error if this situation occurs, so it's perhaps a low-priority item, but I think it's nevertheless useful to have (for example, neither Alex, Dash or I knew about the addition of the env variables and were met with an empty page).

### PR DESCRIPTION
**Pull request by nortonandreev**
Resolves #1317

Screenshot 2024-03-07 at 14 46 06

### CODE REVIEW

File: web-wallet/src/routes/(app)/dashboard/+page.svelte [hunk 1]
```diff
@@ -77,6 +78,23 @@
...
+      <h3>No Contracts Enabled</h3>
+      <p>
+        It appears that no contracts are currently enabled. To access the full
+        range of functionalities, enabling contracts is essential.
+      </p>
+      <h4>For Developers:</h4>
+      <p>
+        If you're in the midst of development and have encountered this message,
+        it's possible that the necessary contract settings have not been
+        configured or activated as expected.
```
[the remark this answers is not in the document]
Comment (nortonandreev) [reply web-wallet/src/routes/(app)/dashboard/+page.svelte]: I have shortened it. I have also wrapped this section within a conditional block so that it appears only on a development env, as suggested. 👍

File: web-wallet/src/routes/(app)/dashboard/+page.svelte [hunk 2]
```diff
@@ -77,6 +78,21 @@
     tokens={balance.value}
   />
 
+  {#if hasNoEnabledContracts}
```
Comment (deuch13) [inline web-wallet/src/routes/(app)/dashboard/+page.svelte:81]: This does not account for the case where the ENV variables are not even defined.
If `VITE_CONTRACT_STAKE_DISABLED` or `VITE_CONTRACT_TRANSFER_DISABLED` are not present the app considers that both or just one of them is enabled.

**Review by deuch13 — CHANGES_REQUESTED** [review]

File: web-wallet/src/routes/(app)/dashboard/+page.svelte (hunk 2 above)
Comment (nortonandreev) [reply web-wallet/src/routes/(app)/dashboard/+page.svelte:81]: You're right. I will think on how to handle this (in the best way).

Comment (deuch13) [reply web-wallet/src/routes/(app)/dashboard/+page.svelte:81]: I would add extra validation here https://github.com/dusk-network/rusk/blob/93c3ea71ade64d8ae6442734429a76aa3099397e/web-wallet/src/lib/contracts/contract-descriptors.js#L10 as this is the main setter of the enabled/disabled contracts.

Comment (nortonandreev) [reply web-wallet/src/routes/(app)/dashboard/+page.svelte:81]: I do agree, it contains the logic in one place. Have a look [now](https://github.com/dusk-network/rusk/pull/1427/files#diff-abdab69d356c20c44fdc6355770a9b7d43d87c6e2f733899c867de12aedba8faR10-R12).

Thanks again for spotting this! 👏

**Review by deuch13 — APPROVED** [review]
