### PR TITLE
web-wallet: Add memo field in send flow

### LINKED ISSUE #3112: web-wallet: Add memo field
The user should have the ability to add a custom `memo` value when sending a transaction.

The [Figma design ](https://www.figma.com/design/z6UnA0BtMBUKIcCXD975um/Wallet-Extension-(JULY-26th)?node-id=6207-158872&node-type=canvas&t=8Gx1YIHAIZxCv6Ww-0)includes this field, but it is incorrectly labelled as "payload".

### PR DESCRIPTION
**Pull request by kieranhall**
Resolves #3112

### CODE REVIEW

File: web-wallet/src/lib/components/Send/Send.svelte [hunk 1]
```diff
@@ -188,7 +195,7 @@
         </div>
         <Textbox
           required
-          className={`operation__send-address ${!addressInfo.isValid ? "operation__send-address--invalid" : ""}`}
+          className={`operation__send-address ${sendToAddress && !addressInfo.isValid ? "operation__send-address--invalid" : ""}`}
```
Comment (ascartabelli) [inline web-wallet/src/lib/components/Send/Send.svelte:198]: Maybe using our usual `makeClassName` function makes it clearer.

File: web-wallet/src/lib/components/Send/Send.svelte [hunk 2]
```diff
@@ -221,6 +228,23 @@
             </p>
           </Banner>
         {/if}
+        <div class="operation__address-wrapper">
+          <p>Memo</p>
+          <Switch
+            bind:showMemo
+            on:change={() => {
+              showMemo = !showMemo;
+            }}
```
Comment (ascartabelli) [inline web-wallet/src/lib/components/Send/Send.svelte:237]: could this be simply `bind:value={showMemo}`?

File: web-wallet/src/lib/components/Send/Send.svelte [hunk 3]
```diff
@@ -355,7 +379,13 @@
     <WizardStep step={3} {key} showNavigation={false}>
       <OperationResult
         errorMessage="Transaction failed"
-        operation={execute(sendToAddress, sendAmountInLux, gasPrice, gasLimit)}
+        operation={execute(
+          sendToAddress,
+          sendAmountInLux,
+          gasPrice,
+          gasLimit,
+          memo
```
Comment (ascartabelli) [inline web-wallet/src/lib/components/Send/Send.svelte:387]: Nitpicking: I'd leave the gas arguments as last for consistency with other methods.

File: web-wallet/src/lib/contracts/executeSend.js [hunk 4]
```diff
@@ -3,16 +3,17 @@ import { Gas } from "$lib/vendor/w3sper.js/src/mod";
 
 import { walletStore } from "$lib/stores";
 
-/** @type {(to: string, amount: bigint, gasPrice: bigint, gasLimit: bigint) => Promise<string>} */
-const executeSend = (to, amount, gasPrice, gasLimit) => {
+/** @type {(to: string, amount: bigint, gasPrice: bigint, gasLimit: bigint, memo: any) => Promise<string>} */
```
Comment (ascartabelli) [inline web-wallet/src/lib/contracts/executeSend.js:6]: Shouldn't be string the type for "memo"?

(see above about the arguments order)

File: web-wallet/src/lib/stores/stores.d.ts [hunk 5]
```diff
@@ -139,7 +139,8 @@ type WalletStoreServices = {
   transfer: (
     to: string,
     amount: bigint,
-    gas: import("$lib/vendor/w3sper.js/src/mod").Gas
+    gas: import("$lib/vendor/w3sper.js/src/mod").Gas,
+    memo: any
```
Comment (ascartabelli) [inline web-wallet/src/lib/stores/stores.d.ts:143]: See above about the type.

File: web-wallet/src/lib/transactions/transactions.d.ts [hunk 6]
```diff
@@ -4,5 +4,6 @@ type Transaction = {
   direction: "In" | "Out";
   fee: number;
   id: string;
+  memo?: string | Uint8Array;
```
Comment (ascartabelli) [inline web-wallet/src/lib/transactions/transactions.d.ts:7]: Two questions: 
- are you sure that this can be an Uint8Array?
- are you sure that the field is optional? Not sure, but I thought it's always there but can be `null`.

File: web-wallet/src/lib/stores/walletStore.js [hunk 7]
```diff
@@ -380,14 +380,16 @@ async function sync(fromBlock) {
...
-const transfer = async (to, amount, gas) =>
+const transfer = async (to, amount, gas, memo) =>
   sync()
     .then(networkStore.connect)
     .then((network) => {
       const tx = bookkeeper
         .as(getCurrentProfile())
         .transfer(amount)
         .to(to)
+        // @ts-ignore we don't have access to the AddressTransfer type
```
Comment (ascartabelli) [inline web-wallet/src/lib/stores/walletStore.js:391]: we don't need the `@ts-ignore` here

**Review by ascartabelli — COMMENTED** [review]
Left some observations, good to merge otherwise, but: I think you need to add a commit to make the same changes in the "official" w3sper.

**Review by herr-seppia — DISMISSED** [review]
Pls split the commit for each module

**Review by ascartabelli — APPROVED** [review]
Good to merge, thanks!

Remember to open a PR to update w3sper as well.
