### PR TITLE
consensus: Support open-consensus-mode in event_loop

### LINKED ISSUE #1907: Do not start over when reaching last iteration
#### Summary

Currently, when the last iteration timeout expires, the iteration counter goes back to 0. This is a wrong behavior.

#### Possible Solution

When reaching the last iteration, keep consensus there indefinitely until either a Quorum or an Emergency Block is received for the round.

### PR DESCRIPTION
**Pull request by goshawk-3**
fixes #1907

### CODE REVIEW

File: consensus/src/consensus.rs [hunk 1]
```diff
@@ -186,7 +184,7 @@ impl<T: Operations + 'static, D: Database + 'static> Consensus<T, D> {
                 ru.base_timeouts.clone(),
             );
 
-            while iter < CONSENSUS_MAX_ITER {
```
[the remark this answers is not in the document]
Comment (fed-franz) [reply consensus/src/consensus.rs:189]: I agree. When reaching last iteration we'll want to exit the loop and wait for the Emergency Block

[the remark this answers is not in the document]
Comment (herr-seppia) [reply consensus/src/consensus.rs:189]: > I agree. When reaching last iteration we'll want to exit the loop and wait for the Emergency Block

I disagree. When we'll implement the emergency block, we should NOT EXIT the loop when the last iteration is reached.
We should still wait for relaxed iterations messages and, in the meanwhile, we should request the emergency block.

[the remark this answers is not in the document]
Comment (fed-franz) [reply consensus/src/consensus.rs:189]: By exiting the loop I didn't mean terminate the execution. 
I meant stop running this loop and handle the situation accordingly (send the EB request, and listen for all messages that could end this round).
I simply dislike having the loop (which is intended to execute steps) get "stuck" on the last iteration just to wait on stuff.

[the remark this answers is not in the document]
Comment (herr-seppia) [reply consensus/src/consensus.rs:189]: I believe we are going out of scope.
We should not take into consideration EmergencyBlock while reviewing this PR.

My original RFC was simply about get back to original while and panic after (just to notice it in case something goes wrong while testing)
```diff
-            while iter < CONSENSUS_MAX_ITER {
+            loop {
```

Said that, I believe that this PR is properly addressing the target issue

**Review by herr-seppia — DISMISSED** [review]
LGTM

File: consensus/src/execution_ctx.rs [hunk 2]
```diff
@@ -126,21 +135,46 @@ impl<'a, DB: Database, T: Operations + 'static> ExecutionCtx<'a, DB, T> {
...
+
                     if let Some(step_result) =
                         self.process_inbound_msg(phase.clone(), msg).await
                     {
+                        if open_consensus_mode && !success_quorum {
+                            // In open consensus mode, consensus step is
+                            // terminated only in case of a success quorum
+                            continue;
+                        }
+
```
Comment (herr-seppia) [inline consensus/src/execution_ctx.rs:177]: I'm not sure about this for the following reasons:
- Having a success Quorum doesn't mean we should stop the consensus, it should be terminated after the block is accepted
- What if the quorum refers to a previous iteration collected during the emerency mode? Returning here would increase the current iteration

Comment (fed-franz) [reply consensus/src/execution_ctx.rs:177]: According to the current specifications, the emergency mode runs until a Success Quorum is reached (or an Emergency Block). That is, we conclude the round as soon as a valid block for the round has been produced. So that part I think it's correct, unless I'm missing something in your comment.

On the other hand, I now have my own doubts on whether Quorum messages are handled properly by `process_inbound_msg`... AFAICS, the function only takes step messages into account, returning Some if a Ratification messages reach a quorum.

Comment (herr-seppia) [reply consensus/src/execution_ctx.rs]: > * Having a success Quorum doesn't mean we should stop the consensus, it should be terminated after the block is accepted

As discussed, I've changed the open_consensus_mode to ignore quorum.

> * What if the quorum refers to a previous iteration collected during the emerency mode? Returning here would increase the current iteration

As analyzed, the process_from_past never return `Some`.
As discussed I changed to code to explicitly return `None`

File: consensus/src/execution_ctx.rs [hunk 3]
```diff
@@ -126,11 +133,22 @@ impl<'a, DB: Database, T: Operations + 'static> ExecutionCtx<'a, DB, T> {
         &mut self,
         phase: Arc<Mutex<C>>,
     ) -> Result<Message, ConsensusError> {
-        debug!(event = "run event_loop");
+        let open_consensus_mode = self.last_step_running();
+
+        // When consensus is in open_consensus_mode then it keeps Ratification
+        // step running infinitely until either a valid block or
```
Comment (fed-franz) [inline consensus/src/execution_ctx.rs:139]:
```suggestion
        // step running indefinitely until either a valid block or
```

File: consensus/src/execution_ctx.rs [hunk 4]
```diff
@@ -141,6 +159,14 @@ impl<'a, DB: Database, T: Operations + 'static> ExecutionCtx<'a, DB, T> {
                     if let Some(step_result) =
                         self.process_inbound_msg(phase.clone(), msg).await
                     {
+                        if open_consensus_mode {
+                            // In open consensus mode, consensus step is never
+                            // terminated.
+                            // The acceptor will cancel the consensus if the
```
Comment (fed-franz) [inline consensus/src/execution_ctx.rs:165]:
```suggestion
                            // The acceptor will cancel the consensus if a
```

**Review by fed-franz — COMMENTED** [review]
LGTM
A couple of comments to fix.

**Review by fed-franz — APPROVED** [review]
