### PR TITLE
web-wallet: Add Address validation (Transfer flow)

### LINKED ISSUE #1377: Address validation
#### Summary
When sending a transaction, I'm allowed to fill in whatever I want in the "Enter address" field. From an UX perspective, it would be nice if I'm either informed or not allowed to click "next" if I'm using an invalid address.

image

Because this will inevitably lead to a failed transaction: 

image

#### Possible solution design or implementation
Introduce address validation. Check whether the address the user fills in adheres to our address format, 87/88 character long string in base58 format.

The way this gets indicated to the user can be done in multiple ways:
1. Enable `next` only if the user filled in a valid address.
2. Warn the user if they click `next` with an incorrect address.
4. Warn the user on the review transaction screen that the address is not valid.

#### Additional context

There is a [PR open](https://github.com/dusk-network/dusk-wallet-js/pull/56) on the `dusk-wallet-js` repo that introduces a validation function.

### PR DESCRIPTION
**Pull request by nortonandreev**
Resolves #1377

**Visuals:**
Screenshot 2024-02-20 at 18 44 40

I have followed the same approach as what we have with the Gas Settings component – where the input is red, when invalid, and the reason why the validation has failed is not displayed. To be candid, I am not a huge fan of this approach, as it's not user-friendly. However, we would need to think about how to properly give feedback to the user and apply the same pattern app-wide.

### CODE REVIEW

**Review by HDauven — DISMISSED** [review]
LGTM

No strong opinion about the UX flow, but I do agree it's not ideal.

There's multiple approaches you can take with this, but I'll leave it up to you to decide what's best. Or based on community feedback/similar wallet applications.

File: web-wallet/src/lib/dusk/string/validateAddress.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ * Validates a Dusk address, with feedback on failure or success.
+ * This function is carried over from
+ * [dusk-wallet-js repo](https://github.com/dusk-network/dusk-wallet-js/blob/71ac65a5105757768bf1af56898a7969a3e06c11/src/keys.js)
+ * @param {String} address The public spent key to validate.
+ * @returns {{isValid: boolean, reason: string}} An object with two keys:
+ *  - `isValid` {Boolean} - true if the address is valid, false if invalid.
+ *  - `reason` {String} - describes why the address is invalid or confirms if it is valid.
+ */
+export default function validateAddress (address) {
+	const regex = /^[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{87,88}$/;
```
Comment (ascartabelli) [inline web-wallet/src/lib/dusk/string/validateAddress.js:11]: Some questions here @HDauven :
- the capital "i" and the lower case "l" are excluded on purpose because of visual similarity, right? (I would use character ranges anyway to help readability)
- why do you make a regexp to test the whole address (length included) if the length is checked otherwise to give a different error message? Isn't it faster to [search](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search) for the first occurrence of an invalid character (haven't tried, and performance won't matter much here, but still)? 

But more importantly: why don't we make a PR to have the `dusk-wallet-js` expose this function instead of maintaining a copy of it here?

Comment (nortonandreev) [reply web-wallet/src/lib/dusk/string/validateAddress.js:11]: > But more importantly: why don't we make a PR to have the `dusk-wallet-js` expose this function instead of maintaining a copy of it here?

Matteo has responded [here](https://github.com/dusk-network/dusk-wallet-js/pull/56#issuecomment-1954015211).

Based on that, Hein and I discussed the best way going forward, at least for the time being, might be porting the validator as a utility function in our code – as we don't know what the plan is, if any, to have it accessible from elsewhere, while I think that allowing the user to progress with a malformed address is bad experience that we could easily resolve.

Comment (ascartabelli) [reply web-wallet/src/lib/dusk/string/validateAddress.js:11]: > > But more importantly: why don't we make a PR to have the `dusk-wallet-js` expose this function instead of maintaining a copy of it here?
> 
> Matteo has responded [here](https://github.com/dusk-network/dusk-wallet-js/pull/56#issuecomment-1954015211).
> 
> Based on that, Hein and I discussed the best way going forward, at least for the time being, might be porting the validator as a utility function in our code – as we don't know what the plan is, if any, to have it accessible from elsewhere, while I think that allowing the user to progress with a malformed address is bad experience that we could easily resolve.

Ok, my bad: I thought it was merged there.

Comment (HDauven) [reply web-wallet/src/lib/dusk/string/validateAddress.js:11]: > Some questions here @HDauven :
> 
> * the capital "i" and the lower case "l" are excluded on purpose because of visual similarity, right? (I would use character ranges anyway to help readability)

Correct, same with o/O/0.

> * why do you make a regexp to test the whole address (length included) if the length is checked otherwise to give a different error message? Isn't it faster to [search](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search) for the first occurrence of an invalid character (haven't tried, and performance won't matter much here, but still)?

You sure can do that. I ported it from a different use case and morphed it into a multi-check. Checking for invalid characters would be a great improvement in my opinion, since it'll explicitly show which characters are invalid towards the reader of the code.

Comment (nortonandreev) [reply web-wallet/src/lib/dusk/string/validateAddress.js]: I have tweaked the regex check with the `search` method. Have a look [here](https://github.com/dusk-network/rusk/blob/3258ad8494974fb111b7323cbe096d410dbb3d80/web-wallet/src/lib/dusk/string/validateAddress.js).

cc: @ascartabelli

File: web-wallet/src/lib/dusk/string/validateAddress.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
+/**
+ * Validates a Dusk address, with feedback on failure or success.
+ * @param {String} address The public spent key to validate.
+ * @returns {{isValid: boolean, reason: string}} An object with two keys:
+ *  - `isValid` {Boolean} - true if the address is valid, false if invalid.
+ *  - `reason` {String} - describes why the address is invalid or confirms if it is valid.
+ */
+export default function validateAddress (address) {
+	const regex = /[^\w]/g;
```
Comment (ascartabelli) [inline web-wallet/src/lib/dusk/string/validateAddress.js:9]: This way you are including invalid characters though.

Write some expectations failing with the most common ones like `O`, `0` `l` and `I`.

(also: no need to define the regex here as it's not used elsewhere: just pass it to the search method, and no need to use the `g` flag)

**Review by ascartabelli — CHANGES_REQUESTED** [review]

File: web-wallet/src/lib/dusk/string/validateAddress.js (hunk 2 above)
Comment (ascartabelli) [reply web-wallet/src/lib/dusk/string/validateAddress.js:9]: > So we are sure that no address can contain O, 0 l or I?

That I don't know: it's what @HDauven said.

> What are others invalid characters you can think of that you would like me to include?
> 
> Generally, when you mentioned this approach, I was worried that blacklisting all invalid characters might be trickier than whitelisting all the valid ones.

I'm sorry if I gave that impression, but I meant no such thing: I would, as you did, use a negated character class (`[^xyx]`), as it's easier.
I was just suggesting to use ranges, e.g. `[^1-9A-HJ-NP-Za-km-z]` (don't take this for granted as I wrote it here without checking).

Comment (ascartabelli) [reply web-wallet/src/lib/dusk/string/validateAddress.js:9]: > From what I can see on the web, Bitcoin addresses use Base58Check which excludes "0" (zero), "O" (uppercase o), "l" (lowercase L), and "I" (uppercase i). Just wanted to confirm we do the same?

That's what was in his original regex

Comment (HDauven) [reply web-wallet/src/lib/dusk/string/validateAddress.js:9]: We indeed adhere to the Bitcoin Base58Check AFAIK

Comment (nortonandreev) [reply web-wallet/src/lib/dusk/string/validateAddress.js]: > (also: no need to define the regex here as it's not used elsewhere: just pass it to the search method, and no need to use the g flag)

I prefer to have the regex defined as a const within the function, as it improves readability IMO.

I have removed the `g` flag tho.

File: web-wallet/CHANGELOG.md [hunk 3]
```diff
@@ -10,16 +10,19 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
...
+- Change Get Quote API Endpoint to env variable [#1311]
+
 ### Removed
 
 - Remove the use of `checkValidity()` in Send and Stake flow amounts validity checks [#1391]
 
 ### Fixed
 
-- Fix typo in routes/welcome/__tests__/page.spec.js [#1445]
+- Fix typo in routes/welcome/tests/page.spec.js [#1445]
```
Comment (ascartabelli) [inline web-wallet/CHANGELOG.md:25]: You could have wrapped the real name in backticks instead.

File: web-wallet/CHANGELOG.md [hunk 4]
```diff
@@ -107,11 +110,8 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 [#1423]: https://github.com/dusk-network/rusk/issues/1423
 [#1391]: https://github.com/dusk-network/rusk/issues/1391
 [#1417]: https://github.com/dusk-network/rusk/issues/1417
-<<<<<<< HEAD
```
Comment (ascartabelli) [inline web-wallet/CHANGELOG.md:110]: Thanks!

File: web-wallet/src/lib/dusk/string/__tests__/validateAddress.spec.js [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+		// Contains an invalid character (0)
+		"47jNTgAhzn0KCKF3msCfvKg3k1P1QpPCLZ3HG3AoNp87sQ5WNS3QyjckYHWeuXqW7uvLmbKgejpP8Xkcip89vnMM",
+
+		// Contains an invalid character (O)
+		"47jNTgAhznOKCKF3msCfvKg3k1P1QpPCLZ3HG3AoNp87sQ5WNS3QyjckYHWeuXqW7uvLmbKgejpP8Xkcip89vnMM",
+
+		// Contains an invalid character (l)
+		"47jNTgAhznlKCKF3msCfvKg3k1P1QpPCLZ3HG3AoNp87sQ5WNS3QyjckYHWeuXqW7uvLmbKgejpP8Xkcip89vnMM",
+
+		// Contains an invalid character (l)
```
Comment (ascartabelli) [inline web-wallet/src/lib/dusk/string/__tests__/validateAddress.spec.js:44]: I think you meant capital "i"

**Review by ascartabelli — CHANGES_REQUESTED** [review]
Just a little typo in a comment

File: web-wallet/CHANGELOG.md (hunk 3 above)
Comment (nortonandreev) [reply web-wallet/CHANGELOG.md]: Should have been escaped with "\_\_", it's done now.

**Review by ascartabelli — APPROVED** [review]
