### PR TITLE
Fix block transactions tree

### LINKED ISSUE #1702: Transactions in block are malleable
**Describe the bug**
Within a block, the initial transaction integrity check is performed by verifying the "txroot" field. This "txroot" field represents the root of a Merkle tree containing the hash of the transaction list in the order they are executed.

However, the current implementation utilizes the transaction IDs as hashes, which do not incorporate zero-knowledge proof (zk-proof). 
Consequently, if a block were to be manipulated to include a transaction with an invalid proof, it would pass the initial check but fail during acceptance (so no harm for the network)

It is suggested to modify the hash used for inclusion in the Merkle tree by calculating it over the entire transaction in its serialized form, thereby incorporating all relevant information including zk-proof.

### PR DESCRIPTION
**Pull request by herr-seppia**
Resolves #1702

### CODE REVIEW

File: node-data/src/ledger.rs [hunk 1]
```diff
@@ -99,6 +99,9 @@ pub struct SpentTransaction {
 
 impl Transaction {
     pub fn hash(&self) -> [u8; 32] {
```
Comment (goshawk-3) [inline node-data/src/ledger.rs:101]: Shouldn't we remove/make private `hash(..)` method to avoid its misuse?

Comment (herr-seppia) [reply node-data/src/ledger.rs:101]: Hash is currently used by the consensus to create the merkletree, so I cannot remove or reduce the visibility.
I can move this outside or just add some doc comments explaining the differences

Comment (goshawk-3) [reply node-data/src/ledger.rs:101]: > Consequently, if a block were to be manipulated to include a transaction with an invalid proof, it would pass the initial check but fail during acceptance (so no harm for the network)

My (maybe mis)understanding here is that we also need to use `tx_id()` for calculating `merkletree` in the (consensus) Block generator too.

**Review by goshawk-3 — APPROVED** [review]
LGTM
