### PR TITLE
Fsm update

### LINKED ISSUE #2410: consensus: Stalled FSM is not working
#### Summary

In a recent test, the following scenario occurred:

Node N accepted block 5 at iteration 1, while the rest of the network moved on with block 5 at iteration 6.
N correctly rejected block 5 with iteration 6 when received it from the network. 
However, once stalled, N should switch to block 5 iteration 6. Instead it remains stalled indefinitely.

The same occurred to several other nodes.

#### Detailed Description

```
2024-09-16T14:02:52.207920Z node 0 accepts Block 4 iter 7
{"timestamp":"2024-09-16T14:02:52.207920Z","level":"INFO","event":"block accepted","height":4,"iter":7,"hash":"ecc79023c7997508...587228a60a88355d","txs":0,"state_hash":"ebc2965c4b58785c...62ce8cd2135ae74a","fsv_bitset":15523759,"ssv_bitset":2719423,"block_time":111,"generator":"23hcRjNqzKUhcHev","dur_ms":"34","label":"Attested(1)","target":"node::chain::acceptor"}

2024-09-16T14:03:49.104793Z node 64 accepts Block 4 iter 7
{"timestamp":"2024-09-16T14:03:49.104793Z","level":"INFO","event":"block accepted","height":4,"iter":7,"hash":"ecc79023c7997508...587228a60a88355d","txs":0,"state_hash":"ebc2965c4b58785c...62ce8cd2135ae74a","fsv_bitset":15523759,"ssv_bitset":2719423,"block_time":111,"generator":"23hcRjNqzKUhcHev","dur_ms":"37","label":"Attested(1)","target":"node::chain::acceptor"}


2024-09-16T14:04:32.410539Z node 0 accepts Block 5 iter 6
{"timestamp":"2024-09-16T14:04:32.410539Z","level":"INFO","event":"block accepted","height":5,"iter":6,"hash":"f59bfd05df2dee25...427696f7f9419d1d","txs":0,"state_hash":"82eda84098409ab1...d05425663264f00a","fsv_bitset":15622029,"ssv_bitset":23887245,"block_time":98,"generator":"o6Ckan2efbGTbJRS","dur_ms":"21","label":"Accepted(6)","target":"node::chain::acceptor"}

2024-09-16T14:04:35.768337Z   nodo 64 accepts Block 5 iter 1
{"timestamp":"2024-09-16T14:04:35.768337Z","level":"INFO","event":"block accepted","height":5,"iter":1,"hash":"ea326a56994a63a0...6f78572099f95af1","txs":0,"state_hash":"356bc8712ca68be0...5b3226c95f74a8cb","fsv_bitset":1793949,"ssv_bitset":7176141,"block_time":24,"generator":"26DsWXiCrNxkmCZ1","dur_ms":"19","label":"Attested(1)","target":"node::chain::acceptor"}


2024-09-16T14:04:35.768337Z   node 64 receives Block 5 iter 6 and discards it (correctly)
{"timestamp":"2024-09-16T14:04:35.783002Z","level":"ERROR","event":"fallback failed","err":"iteration 6 is higher than the current 1\n\nStack backtrace:\n  }

2024-09-16T14:07:40.238869Z node 0 finalizes Block 5 iter 6 (after 18 blocks)
{"timestamp":"2024-09-16T14:07:40.238869Z","level":"INFO","event":"block finalized","src":"rolling_finality","current_height":23,"height":5,"finalized_after":18,"hash":"f59bfd05df2dee25...427696f7f9419d1d","state_root":"82eda84098409ab1...d05425663264f00a","target":"node::chain::acceptor"}
```

Block 5 iter 6 is never received again by node 0.
This might be due to: (1) node 0 never requests block 5, or (2) block 5 is discarded when received.
Discarding might be due to (1) dupemap, (2) `attach_att_if_needed` returning None due to missing Attestation.

StalledFSM also seems not to be receiving blocks, so StalledOnFork is never activated.

#### Relevant Context

A proper behavior from node 0 upon receiving block 5 iter 6 would be to respond with block 5 iter 1.
See #2411

#### Possible Solution

Requires further investigation

### PR DESCRIPTION
**Pull request by goshawk-3**
fixes #2410
- node: Ensure that an error in FSM does not affect the stalled_sm
- Use GetBlocks
- Rerequest blocks if it remains too long in STALLED

### CODE REVIEW

File: node/src/chain/fsm.rs [hunk 1]
```diff
@@ -255,18 +256,15 @@ impl<N: Network, DB: database::DB, VM: vm::VMExecution> SimpleFSM<N, DB, VM> {
...
+
+            // Ensure that an error in FSM does not affect the stalled_sm
+            fsm_res?;
         }
-        // FIXME: The block should return only if accepted. The current issue is
-        // that the impl of State::on_block_event doesn't return always the
-        // accepted block, so we can't rely on them
-        //
-        // Due to this issue, we reset the outer timeout even if we are not
-        // accepting the received block
```
Comment (herr-seppia) [inline node/src/chain/fsm.rs:269]: Has this been fixed?

File: node/src/chain/stall_chain_fsm.rs [hunk 2]
```diff
@@ -205,29 +219,33 @@ impl<DB: database::DB, N: Network, VM: VMExecution> StalledChainFSM<DB, N, VM> {
...
-        let from = last_final_block + 1;
-        let to = self.tip.0.height + 1;
-
-        info!(event = "chain.requesting_blocks", from, to,);
-
-        let mut inv = Inv::new(0);
-        for height in from..to {
-            inv.add_block_from_height(height);
+    async fn on_heartbeat_in_stalled(&mut self) {
+        if let State::Stalled(timestamp) = self.state {
```
Comment (fed-franz) [inline node/src/chain/stall_chain_fsm.rs:223]: We already know the state is Stalled here, since it's checked in `on_heartbeat_event`. Maybe consider removing the `if` condition

File: node/src/chain/fsm.rs (hunk 1 above)
Comment (goshawk-3) [reply node/src/chain/fsm.rs:269]: The return value is not in use since we deprecated `ACCEPT_TIMEOUT` + on_idle from chain

**Review by fed-franz — APPROVED** [review]
LGTM

File: node/src/chain/fsm.rs (hunk 1 above)
Comment (fed-franz) [reply node/src/chain/fsm.rs:269]: While the issue does not affect the timeout reset anymore, it is still true we sometimes return the block even it it's not accepted.
I agree on removing this comment, but let's update the description of `on_block_event` to state this fact, so we don't assume in the future that this function only returns a block if accepted.

File: node/src/chain/stall_chain_fsm.rs (hunk 2 above)
Comment (goshawk-3) [reply node/src/chain/stall_chain_fsm.rs:223]: Not a blocker (will be addressed in next PR)

File: node/src/chain/fsm.rs (hunk 1 above)
Comment (goshawk-3) [reply node/src/chain/fsm.rs:269]: Not a blocker (will be addressed in next PR)
