### PR TITLE
transfer-contract: Add tests for failing conversions

### LINKED ISSUE #2969: transfer-contract: Add tests for failing conversions
#### Summary
Add tests to check that conversion with the incorrect transaction model is not possible.

#### Detailed Description
When attempting a conversion, the transaction model from which the funds are sent must match the transaction model used to pay gas.
This means that:
- converting moonlight DUSK to phoenix DUSK can only be done with a moonlight transaction
- converting phoenix DUSK to moonlight DUSK can only be done with a phoenix transaction.

### PR DESCRIPTION
**Pull request by moCello**
Resolves #2969

### CODE REVIEW

File: contracts/transfer/tests/moonlight.rs [hunk 1]
```diff
@@ -478,6 +478,138 @@ fn convert_to_phoenix() {
...
+    assert_eq!(leaves.len(), 0, "no new leaves should have been created");
+
+    let nullifier = vec![nullifier];
+    let existing_nullifers = existing_nullifiers(session, &nullifier)
+        .expect("Querrying the nullifiers should work");
+    assert_eq!(
+        Vec::<BlsScalar>::new(),
+        existing_nullifers,
+        "the note shouldn't have been nullified"
+    );
```
Comment (Neotamandua) [inline contracts/transfer/tests/moonlight.rs:610]:
```suggestion
    assert!(
        existing_nullifers.is_empty(),
        "the note shouldn't have been nullified"
    );
```

File: contracts/transfer/tests/phoenix.rs [hunk 2]
```diff
@@ -965,6 +966,143 @@ fn contract_withdraw() {
...
+    session
+        .call::<_, ()>(
+            TRANSFER_CONTRACT,
+            "add_account_balance",
+            &(moonlight_pk, CONVERSION_VALUE),
+            GAS_LIMIT,
+        )
+        .expect("Inserting genesis account should succeed");
+
+    // make sure the moonlight account doesn't own any funds before the
```
Comment (Neotamandua) [inline contracts/transfer/tests/phoenix.rs:998]: Shouldn't this be, that it owns CONVERSION_VALUE?

File: contracts/transfer/tests/phoenix.rs [hunk 3]
```diff
@@ -965,6 +966,143 @@ fn contract_withdraw() {
...
+    // conversion
+    let moonlight_account = account(&mut session, &moonlight_pk)
+        .expect("Getting account should succeed");
+    assert_eq!(
+        moonlight_account.balance, CONVERSION_VALUE,
+        "The moonlight account should have the max gas before the transaction"
```
Comment (Neotamandua) [inline contracts/transfer/tests/phoenix.rs:1004]:
```suggestion
        "The moonlight account should have the conversion value before the transaction"
```
Same as with the comment above?

File: contracts/transfer/tests/phoenix.rs [hunk 4]
```diff
@@ -965,6 +966,143 @@ fn contract_withdraw() {
...
+    );
+
+    let receipt = execute(session, tx).expect("Executing TX should succeed");
+
+    // check that the transaction execution panicked with the correct message
+    assert!(receipt.data.is_err());
+    assert_eq!(
+        format!("{}", receipt.data.unwrap_err()),
+        String::from("Panic: Expected Moonlight TX, found Phoenix"),
+        "The attempted conversion from phoenix to moonlight when paying gas with moonlight should error"
```
Comment (Neotamandua) [inline contracts/transfer/tests/phoenix.rs:1065]:
```suggestion
        "The attempted conversion from moonlight to phoenix when paying gas with phoenix should error"
```

**Review by Neotamandua — COMMENTED** [review]
Looks good. Found some comments that seem to be off and added a small suggestion to the nullifier assertion

**Review by Neotamandua — APPROVED** [review]
LGTM
