### PR TITLE
 Transaction failures should be returned upon block acceptance

### LINKED ISSUE #599: Transaction failures should be returned upon block acceptance
**Describe what you want implemented** 
The `Accept`/`Finalize` RPC should return information about transaction failures even if the whole block consists of valid transactions.

**Describe "Why" this is needed**
This is needed to report to the users the status of their transaction and allow for the block explorer to report the error's cause (if available) or, at the very least, just a flag that tells the user that his transaction failed

**Additional Context**
Failures that can be currently reported is the following an enum:
 * out of gas => no further information
 * unknown contract => `ContractID`
 * Contract panics (no granularity, can be an `expect` or an `unwrap`) => `ContractID`, error message.

The `ContractID` is necessary to identify which contract failed. This is because the panic might happen during an inter-contract call.

### PR DESCRIPTION
**Pull request by ZER0**
- Add `Error` type to `ExecutedTransaction`
- rusk: Add Transaction's error conversion and propagation

Resolves  #599

### CODE REVIEW

File: rusk/src/lib/encoding.rs [hunk 1]
```diff
@@ -176,9 +178,46 @@ impl TryFrom<&mut rusk_proto::Transaction> for Transaction {
...
+            Error::Vm(e) => match e {
+                VMError::UnknownContract(id) => {
+                    (Code::UnknownContract, id, format!("{}", e))
+                }
+                VMError::ContractPanic(id, data) => {
+                    (Code::ContractPanic, id, data)
+                }
+                VMError::OutOfGas => (
+                    Code::OutOfGas,
+                    rusk_abi::transfer_contract(),
```
Comment (herr-seppia) [inline rusk/src/lib/encoding.rs:195]: What happen if we run out of gas during a stake? It will result as transfer_contract's error?

Comment (ZER0) [reply rusk/src/lib/encoding.rs:195]: Yes, because the `OutOfGas` is not related to the contract, is related to the transaction, and all the transaction are initiated by the transfer contract's `execute`. So basically the block explorer won't don't display that "this contract" is went out of gas, but that the transaction didn't have enough gas to go through.

Different story is for `UnknownContract` and `ContractPanic`, since if you have contract `A` calling `B` calling `C` you want to know which of those is panicking or it's unknown.

**Review by herr-seppia — APPROVED** [review]
LGTM

**Review by autholykos — APPROVED** [review]
LGTM
